"""Initial migration

Revision ID: 2df8bc45681e
Revises: 
Create Date: 2023-11-23 01:12:57.573234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df8bc45681e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Comment', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Mail', sa.String(length=255), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('Page', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('page',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('ImageData', sa.LargeBinary(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('URL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('post',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('ImageData', sa.LargeBinary(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Author', sa.String(length=50), nullable=True),
    sa.Column('URL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('page')
    op.drop_table('comment')
    # ### end Alembic commands ###
