"""Create page table

Revision ID: 5b73d50b82c6
Revises: 1f1fddc27f6b
Create Date: 2023-11-05 22:29:24.274371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b73d50b82c6'
down_revision = '1f1fddc27f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('ImageData', sa.LargeBinary(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('URL', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('page')
    # ### end Alembic commands ###
