"""Create comment table

Revision ID: a9d6a9ea9c74
Revises: 5b73d50b82c6
Create Date: 2023-11-07 01:12:57.648882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d6a9ea9c74'
down_revision = '5b73d50b82c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Comment', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Mail', sa.String(length=255), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('Page', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
