"""initial migration

Revision ID: cb53c561bfe0
Revises: 
Create Date: 2023-10-24 18:14:36.048263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb53c561bfe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('ImageData', sa.LargeBinary(), nullable=True),
    sa.Column('Category', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
