"""Add author and url

Revision ID: e2cb0f25fd11
Revises: cb53c561bfe0
Create Date: 2023-10-24 21:13:11.833688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cb0f25fd11'
down_revision = 'cb53c561bfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Author', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('URl', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('URl')
        batch_op.drop_column('Author')

    # ### end Alembic commands ###
