"""Add User model

Revision ID: f73108bd0cd0
Revises: e2cb0f25fd11
Create Date: 2023-10-26 14:02:20.070112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73108bd0cd0'
down_revision = 'e2cb0f25fd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('admin')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('URL', sa.String(length=255), nullable=True))
        batch_op.alter_column('Date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('URl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('URl', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('Date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('URL')

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
